baseurl = "https://timbrier.com/"
title = "Tim Brier Woodworking"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-uk"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet, brown
  # Use custom.css for your custom styling
  style = "brown"
  description = "A portfolio of woodworking and joinery projects from Tim Brier, a woodworker based in Swinton, Manchester. Hand made wooden gifts, toys and furniture using quality hardwood."
  sidebarAbout = [
    "I'm a hobbyist woodworker based in Manchester, UK. All the projects showcased here were made by hand in my garden shed workshop.",
    "I'm happy to take on comissions, get in touch using the links below.",
    "Originally from Huddersfield, currently based in Urmston, Manchester."
  ]

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "/"
  home = true

  [params.social]
#  email         = "example@example.com"
  instagram     = "timbrier"
#  etsy          = "example-shop-id"
#  phone         = "123456789"
